export const ProjectsActionTypes = {
    GET_PROJECTS: 'GET_PROJECTS',
    GET_PROJECT: 'GET_PROJECT',
    DELETE_PROJECT: 'DELETE_PROJECT',
    PROJECT_ERROR: 'PROJECT_ERROR',
    CLEAR_PROJECTS: 'CLEAR_PROJECTS',
};
