export const ProjectInfoActionTypes = {
    LEAD_SUCCESS: 'LEAD_SUCCESS',
    LEAD_FAILURE: 'LEAD_FAILURE',
    RESOURCE_SUCCESS: 'RESOURCE_SUCCESS',
    RESOURCE_FAILURE: 'RESOURCE_FAILURE',
    TOGGLE_RESOURCE_ADD: 'TOGGLE_RESOURCE_ADD',
    TOGGLE_RESOURCE_INFO: 'TOGGLE_RESOURCE_INFO',
};
