export const ProjectInfoActionTypes = {
    LEAD_OR_MANAGER_SUCCESS: 'LEAD_OR_MANAGER_SUCCESS',
    LEAD_OR_MANAGER_FAILURE: 'LEAD_OR_MANAGER_FAILURE',
    TOGGLE_RESOURCE_ADD: 'TOGGLE_RESOURCE_ADD',
    TOGGLE_RESOURCE_INFO: 'TOGGLE_RESOURCE_INFO',
};
